// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(PadelDbContext))]
    [Migration("20260904063747_EnforceConcurrencyRulesInDatabase")]
    partial class EnforceConcurrencyRulesInDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entities.BalanceDue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SettlementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("UQ_BalancesDue_MatchId");

                    b.HasIndex("MemberId");

                    b.ToTable("BalancesDue");
                });

            modelBuilder.Entity("Core.Domain.Entities.ClosureDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ClosureDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClosureDate");

                    b.HasIndex("SiteId");

                    b.ToTable("ClosureDays");
                });

            modelBuilder.Entity("Core.Domain.Entities.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("Covered")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<string>("SurfaceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("SiteId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Courts_SiteId_Name");

                    b.HasIndex("SiteId", "Number")
                        .IsUnique()
                        .HasDatabaseName("UQ_Courts_SiteId_Number");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("Core.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("CourtId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PaymentDeadline")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PublicSwitchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SlotId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("SlotId");

                    b.HasIndex("CourtId", "Date");

                    b.HasIndex("CourtId", "Date", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("UQ_Matches_CourtId_Date_StartTime")
                        .HasFilter("\"Status\" <> 'Cancelled'");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Core.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("MemberTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Members_Email");

                    b.HasIndex("Matricule")
                        .IsUnique()
                        .HasDatabaseName("UQ_Members_Matricule");

                    b.HasIndex("MemberTypeId");

                    b.HasIndex("SiteId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Core.Domain.Entities.MemberType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MatriculePrefix")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("ReservationWindowDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_MemberTypes_Code");

                    b.ToTable("MemberTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GLOBAL",
                            Label = "Membre global",
                            MatriculePrefix = "G",
                            ReservationWindowDays = 21
                        },
                        new
                        {
                            Id = 2,
                            Code = "SITE",
                            Label = "Membre de site",
                            MatriculePrefix = "S",
                            ReservationWindowDays = 14
                        },
                        new
                        {
                            Id = 3,
                            Code = "LIBRE",
                            Label = "Membre libre",
                            MatriculePrefix = "L",
                            ReservationWindowDays = 5
                        });
                });

            modelBuilder.Entity("Core.Domain.Entities.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int?>("MemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MatchId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Participations_MatchId_MemberId");

                    b.HasIndex("MatchId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Participations_MatchId_SeatNumber");

                    b.ToTable("Participations", t =>
                        {
                            t.HasCheckConstraint("CK_Participations_SeatNumber_Range", "\"SeatNumber\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("Core.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("BalanceDueId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParticipationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BalanceDueId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ParticipationId");

                    b.HasIndex("TransactionReference")
                        .IsUnique()
                        .HasDatabaseName("UQ_Payments_TransactionReference");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Core.Domain.Entities.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("MemberId");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Core.Domain.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("AdminId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Sites_AdminId_Name");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Core.Domain.Entities.SiteSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("MatchDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("MatchPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("RequiredPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Year")
                        .IsUnique()
                        .HasDatabaseName("UQ_SiteSchedules_SiteId_Year");

                    b.ToTable("SiteSchedules");
                });

            modelBuilder.Entity("Core.Domain.Entities.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("SiteScheduleId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SiteScheduleId", "Order")
                        .IsUnique()
                        .HasDatabaseName("UQ_Slots_SiteScheduleId_Order");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Core.Domain.Entities.BalanceDue", b =>
                {
                    b.HasOne("Core.Domain.Entities.Match", "Match")
                        .WithMany("BalancesDue")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Member", "Member")
                        .WithMany("BalancesDue")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Core.Domain.Entities.ClosureDay", b =>
                {
                    b.HasOne("Core.Domain.Entities.Site", "Site")
                        .WithMany("ClosureDays")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Core.Domain.Entities.Court", b =>
                {
                    b.HasOne("Core.Domain.Entities.Site", "Site")
                        .WithMany("Courts")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Core.Domain.Entities.Match", b =>
                {
                    b.HasOne("Core.Domain.Entities.Court", "Court")
                        .WithMany("Matches")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Member", "Organizer")
                        .WithMany("OrganizedMatches")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Slot", "Slot")
                        .WithMany("Matches")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Court");

                    b.Navigation("Organizer");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Core.Domain.Entities.Member", b =>
                {
                    b.HasOne("Core.Domain.Entities.MemberType", "MemberType")
                        .WithMany("Members")
                        .HasForeignKey("MemberTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Site", "Site")
                        .WithMany("Members")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MemberType");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Core.Domain.Entities.Participation", b =>
                {
                    b.HasOne("Core.Domain.Entities.Match", "Match")
                        .WithMany("Participations")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Member", "Member")
                        .WithMany("Participations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Match");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Core.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Core.Domain.Entities.BalanceDue", "BalanceDue")
                        .WithMany("Payments")
                        .HasForeignKey("BalanceDueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Participation", "Participation")
                        .WithMany("Payments")
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BalanceDue");

                    b.Navigation("Member");

                    b.Navigation("Participation");
                });

            modelBuilder.Entity("Core.Domain.Entities.Penalty", b =>
                {
                    b.HasOne("Core.Domain.Entities.Match", "Match")
                        .WithMany("Penalties")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Member", "Member")
                        .WithMany("Penalties")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Core.Domain.Entities.SiteSchedule", b =>
                {
                    b.HasOne("Core.Domain.Entities.Site", "Site")
                        .WithMany("SiteSchedules")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Core.Domain.Entities.Slot", b =>
                {
                    b.HasOne("Core.Domain.Entities.SiteSchedule", "SiteSchedule")
                        .WithMany("Slots")
                        .HasForeignKey("SiteScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteSchedule");
                });

            modelBuilder.Entity("Core.Domain.Entities.BalanceDue", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Core.Domain.Entities.Court", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Core.Domain.Entities.Match", b =>
                {
                    b.Navigation("BalancesDue");

                    b.Navigation("Participations");

                    b.Navigation("Penalties");
                });

            modelBuilder.Entity("Core.Domain.Entities.Member", b =>
                {
                    b.Navigation("BalancesDue");

                    b.Navigation("OrganizedMatches");

                    b.Navigation("Participations");

                    b.Navigation("Payments");

                    b.Navigation("Penalties");
                });

            modelBuilder.Entity("Core.Domain.Entities.MemberType", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Core.Domain.Entities.Participation", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Core.Domain.Entities.Site", b =>
                {
                    b.Navigation("ClosureDays");

                    b.Navigation("Courts");

                    b.Navigation("Members");

                    b.Navigation("SiteSchedules");
                });

            modelBuilder.Entity("Core.Domain.Entities.SiteSchedule", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Core.Domain.Entities.Slot", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
